# Generated by Django 4.0.3 on 2022-03-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointid', models.CharField(max_length=250, null=True)),
                ('BUILDINGNAME', models.CharField(max_length=250, null=True)),
                ('BLOCK', models.CharField(max_length=250, null=True)),
                ('ROAD', models.CharField(max_length=250, null=True)),
                ('FEATURENAME', models.CharField(max_length=250, null=True)),
                ('POSTALCODE', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
