# Generated by Django 4.0.3 on 2022-03-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIFT', '0002_remove_pointinfo_pointid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointinfo',
            name='HIGHWAY',
            field=models.TextField(null=True),
        ),
    ]
