# Generated by Django 4.0.3 on 2022-03-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIFT', '0004_pathcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathcache',
            name='destination',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pathcache',
            name='source',
            field=models.TextField(),
        ),
    ]
