# Generated by Django 4.0.3 on 2022-03-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIFT', '0006_pointinfo_lat_pointinfo_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('driverlat', models.FloatField()),
                ('driverlong', models.FloatField()),
                ('seatNo', models.IntegerField()),
                ('status', models.TextField()),
            ],
        ),
    ]
