# Generated by Django 4.0.3 on 2022-03-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIFT', '0008_drivers_driverid_alter_drivers_driverlat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathcache',
            old_name='Data',
            new_name='graph',
        ),
        migrations.AddField(
            model_name='pathcache',
            name='heuristic',
            field=models.TextField(null=True),
        ),
    ]
